### ISSUE TITLE
CONTRIBUTING.md, branch should be main, not master.

### ISSUE THREAD

**Issue by BitesizedLion** [public-apis-dev/public-apis#11]
The target branch in the CONTRIBUTING.md file is incorrect, the branch should be main, not master, as it does not exist.

https://github.com/public-apis-dev/public-apis/blob/6aab058a06d17d274befcc3c2bda62b381c27c43/CONTRIBUTING.md?plain=1#L60

**Comment by marcelscruz** [comment]
Fixed.
Thank you for reporting it.
