### ISSUE TITLE
Filter APIs by CORS or Auth

### ISSUE THREAD

**Issue by olitreadwell** [public-apis-dev/public-apis#145]
It'd be cool to be able to filter the APIs on https://publicapis.dev/ by whether they require CORS or an API Key.

I probably won't get time to look into doing this at any point soon, but if I find some time I'll give it a shot and ask for feedback.

**Comment by marcelscruz** [comment]
That's a good idea, @olitreadwell, thank you.

The website is maintained by me and it's closed-source, but I'll have a look into that as soon as I can.

**Comment by skulldoggery** [comment]
Your call of course, but since it appears you already have a visual concept of "labels" for each record, maybe a more general ability to search on those? Something like `label:oauth`? 

Just a thought! It might allow for greater extensibility in categorizing API sources without having to mess with the search itself down the road.

**Comment by marcelscruz** [comment]
Thanks for the suggestion @skulldoggery.
It does seem like a reasonable addition to the site.
I have some improvements like that in my backlog, and I'll tackle them asap!

**Comment by skulldoggery** [comment]
You've already mentioned that this is a closed source project, but don't hesitate to reach out if you'd like an extra set of hands for anything! Cheers!

**Comment by marcelscruz** [comment]
@olitreadwell @skulldoggery I've just added filters for cors, https and auth values on the website.

I would appreciate it if you guys could try it and let me know if you find anything wrong.

And again, thanks for the suggestion!

**Comment by olitreadwell** [comment]
This looks great @marcelscruz, is there a way to add a filter for the Auth column to filter by "none" or "No auth"? 

That's the specific use case I'm looking for.

**Comment by marcelscruz** [comment]
Good catch @olitreadwell, thanks!
There's a "No auth" option now. :)

**Comment by skulldoggery** [comment]
Great work, @marcelscruz! Thank you!
