### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by bkil** [public-apis-dev/public-apis#18]
Do you think we could refine the values under CORS? Various services could work from the browser under different circumstances.

* With CORS headers: XHR (and fetch)
* Without CORS headers:
  * Submitting data via HTML `<form>`, CSP reports or `<a ping` link tracking
  * Embedding resources: `<iframe>`, fonts, `<img>`, `<video>`, `<audio>`
  * Getting data via JSONP (or css)
  * Everything else only on the server side

**Comment by marcelscruz** [comment]
Thank you for bringing this idea forth.

For the time being, I suggest we keep the current convention to not deviate too much from [the original project that's going through some issues](https://github.com/public-apis/public-apis/issues/3104).

This repository here is, at least for now, an alternative to the above-mentioned, and if at any moment we decide this situation will be permanent, then we can think about making more significant changes around here.

**Comment by bkil** [comment]
Before contributing, I have researched the situation related to the project, this fork, and the copy & pasted "fork". I have concluded that you will never get the old repository back - deal with it. Just let it go and move on.

**Comment by bkil** [comment]
Are you willing to share owner status with @matheusfelipeog (along with also promoting @pawelborkar @marekdano @yannbertrand), the main contributors named in the issue?

**Comment by marcelscruz** [comment]
Most definitely, if they're willing to work on this fork, I'm happy to give them permission to collaborate.
They've done a great job in the other repo, and I'm sure their contribution here would be just as good.

**Comment by marcelscruz** [comment]
@matheusfelipeog as you seem to be the most active maintainer in the other repo as of lately, what's your take on the suggestion above? Do you see any solution for the original repo, or do you think we should start focusing on a new one?

@bkil gave great suggestions on the other issues he created, and I'd like to hear your thoughts on it moving forward.

**Comment by matheusfelipeog** [comment]
Hi guys 👋

> @matheusfelipeog as you seem to be the most active maintainer in the other repo as of lately, what's your take on the suggestion above? Do you see any solution for the original repo, or do you think we should start focusing on a new one?

At the moment we haven't decided to focus on a new one, but we will consider all the suggestions from the community when we decide which path we are going to take.

As incredible as it may seem, I'm still looking for ways to solve the problem I described in the issue. Any updates on the matter, I will communicate directly in the issue.

**Comment by pawelborkar** [comment]
Hi Guys,
>So for the time being we'll also stay on standby on this repository here waiting on the conclusion of this issue.

I would suggest not to stay on standby with this project and would suggest exploring the suggestions given by @bkil and also other possibilities which the community and the maintainers think would be beneficial to the whole community. As we at the original public apis project are already got standstill. I would suggest to move forward with the possibilities within this project. If the issue in the main project resolves we might wrote a script in accordance with the contributing standards of the public apis project and will copy the entries from this project into that one. So I think you should move forward with the possible great suggestions.
