### ISSUE TITLE
HTTP Dog API is offline, should we remove it?

### ISSUE THREAD

**Issue by Ronkiro** [public-apis-dev/public-apis#191]
[HTTP Dog](https://http.dog/) images are throwing error 500. Should we remove it from list?

![image](https://github.com/public-apis-dev/public-apis/assets/27526023/884d8935-6a4f-41ae-8e6e-096b8b16e518)
![image](https://github.com/public-apis-dev/public-apis/assets/27526023/8fea6122-3ce3-4b1b-88cc-aafc460f0452)

**Comment by Ronkiro** [comment]
Strange, when using ProxySite it still returns 500 for me

![image](https://github.com/public-apis-dev/public-apis/assets/27526023/c4691429-64b7-4292-a012-76c5ae41cb49)

**Comment by marcelscruz** [comment]
Strange indeed.
I'll leave this issue open for a few more days an monitor it.
Thank you for letting me know.

<img width="600" alt="Screenshot 2023-09-04 at 17 24 22" src="https://github.com/public-apis-dev/public-apis/assets/12413903/567de17a-336b-45e3-8e2d-846cdcc4ed60">

**Comment by Ronkiro** [comment]
Your screenshot shown me that the website is actually wrong for me on Google Chrome
![image](https://github.com/public-apis-dev/public-apis/assets/27526023/9125b01d-e0e0-4f8b-99b2-a84ab1827470)

On Edge it works correctly

![image](https://github.com/public-apis-dev/public-apis/assets/27526023/47221343-b0cd-4a64-ba69-b1b712e60ada)

This may be some kind of extension or something local for me. Gonna close as it seems that it's just for me

**Comment by Ronkiro** [comment]
It was really an extension, "CORS unblock".

Disabled it and now all works correctly

![image](https://github.com/public-apis-dev/public-apis/assets/27526023/b0a30cf3-c335-4cf0-b5b6-1bab7d8f1d0b)
