### ISSUE TITLE
Consider removing apilayer products from this list

### ISSUE THREAD

**Issue by LukasGirsch** [public-apis-dev/public-apis#192]
Since apiLayer choose to basically stall the development of the original public-apis list wouldn't it be reasonable to remove their exposure on all other forks?

**Comment by marcelscruz** [comment]
Good catch, I'm on it.

**Comment by LukasGirsch** [comment]
Just wanted to point out that currencylayer.com and exchangeratesapi.io are also owned by apilayer.

**Comment by LukasGirsch** [comment]
They also own: 
https://vatlayer.com/
https://scrapestack.com/
https://serpstack.com/
https://ipapi.com/
https://positionstack.com/

+
https://currencylayer.com/
https://exchangeratesapi.io/
