### ISSUE TITLE
URLBae Compromised

### ISSUE THREAD

**Issue by thebrandonc** [public-apis-dev/public-apis#247]
Hello, it appears a service listed in this repo has been compromised: https://urlbae.com/ (link shortener). I got a Youtube strike as I was previously using their service and my links are now directed to some malicious site. I'll create a PR if I can get to it in time, but just wanted to raise the issue

**Comment by marcelscruz** [comment]
Thank you for letting me know, I'm deleting it now.

**Comment by marcelscruz** [comment]
Deleted on [this commit](https://github.com/public-apis-dev/public-apis/commit/e57229066f363a129dc8340be015c26eb1b9abd7).
