### ISSUE TITLE
Ask all downstream data users to remove all mentions of public-apis

### ISSUE THREAD

**Issue by bkil** [public-apis-dev/public-apis#25]
* Each project (both in source form and their websites) should only link to and only reference _this_ repository, not that of public-apis.
* The lineage, acknowledgement and the situation could be mentioned in the readme here in a few words.
* Wait for #20 and #24 with this.

**Comment by bhaveshsonje** [comment]
Hey, I  am Bhavesh Sonje. How can I contribute to this open source project for my open source class? Please assign me a task.
Contact Me: sonjebhavesh623@gmail.com
GitHub: bhaveshsonje

**Comment by faradeen-ja** [comment]
Hi, I’d love to contribute. Let me know how I can help with open issues?

**Comment by marcelscruz** [comment]
Hi @faradeen-ja, thank you for offering it!

For the time I'd appreciate the help in moving all the open PRs from [public-apis/public-apis](https://github.com/public-apis/public-apis) to this project here.
I've started from oldest to latest, and I've left a comment on those PRs to know if they're done/invalid.
