### ISSUE TITLE
Remove Superheroes API

### ISSUE THREAD

**Issue by domwakeling** [public-apis-dev/public-apis#5]
[Superheroes API](https://superheroapi.com/) site registration expired early June '22, suggest it is (temporarily?) removed from the list

**Comment by kraigee** [comment]
> [Superheroes API](https://superheroapi.com/) site registration expired early June '22, suggest it is (temporarily?) removed from the list

The API should be removed once #8 is merged.

**Comment by marcelscruz** [comment]
#8 is merged.

**Comment by BitesizedLion** [comment]
Should be added back, domain got renewed.
